### ISSUE TITLE
[feature request] toggle to set coordinate system to y-up or y-down

### ISSUE THREAD

**Issue by adam-law** [Spasi/LWJGL-FX#10]
I got pretty far in my work and got my world to screen conversions down to where I want them. I was working under the impression that things were y-up, but I just found out that your project seems to function on y-down, because my conversions cause objects to move in reverse e.g. gravity pulls up, not down, when I take my app out of the FXNode and run it as an LWJGLApplication.

I'd be happy to do the modification, just point me to where it's appropriate to make a change and I'll get around to making a pull request when I have the time.

**Comment by Spasi** [comment]
I don't remember where the inversion happens exactly, but I found [this](https://github.com/Spasi/LWJGL-FX/blob/master/res/gears.fxml#L22): see the `scaleY="-1.0"` on the ImageView.

Note that by default the origin in OpenGL is on the bottom-left, whereas it's on the top-left in JavaFX. For the two to match, you must either flip in OpenGL or JavaFX, but it's best to do the flipping in JavaFX so that your app can also work as an LWJGLApplication without other changes.

**Comment by adam-law** [comment]
great tip. setting the scaleY of the Imageview did the trick and I'll just have to invert the Y values for touch events in XpeInput and things should be set.

thanks :)
